// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKoU_0r4kfABNq9qi_xujAsW9SqbbpcDA',
    appId: '1:1059213750252:web:67fc25e76200f2ba505ac9',
    messagingSenderId: '1059213750252',
    projectId: 'flutter-app-ab2c9',
    authDomain: 'flutter-app-ab2c9.firebaseapp.com',
    storageBucket: 'flutter-app-ab2c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbNgyixkmjigdLuASK8kC2QauZlTNj32M',
    appId: '1:1059213750252:android:75519c60bad5e0dc505ac9',
    messagingSenderId: '1059213750252',
    projectId: 'flutter-app-ab2c9',
    storageBucket: 'flutter-app-ab2c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA93907ppe45IpmGmbNjBUZqu4xvFW4VmI',
    appId: '1:1059213750252:ios:e3bc5d1348061441505ac9',
    messagingSenderId: '1059213750252',
    projectId: 'flutter-app-ab2c9',
    storageBucket: 'flutter-app-ab2c9.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA93907ppe45IpmGmbNjBUZqu4xvFW4VmI',
    appId: '1:1059213750252:ios:9a91ee9a7c428700505ac9',
    messagingSenderId: '1059213750252',
    projectId: 'flutter-app-ab2c9',
    storageBucket: 'flutter-app-ab2c9.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
